### ISSUE TITLE
MukthaNarayan Recommendations

### ISSUE THREAD

**Issue by MukthaNarayan** [githubschool/automatic-waffle#10]
Adding my recommendations for things to do at hometown:
```Fenced code block
- [ ] Branch 1
- [ ] Adding a file to test Issue #1
- [ ] Commit
- [ ] Initiate a Pull Request #1 
- [ ] Request review
- [ ] Make additional changes to PR #1 
- [ ] Get approval
- [ ] Merge PR #1

```

**Comment by MukthaNarayan** [comment]
This exercise is been completed.
